---         # install HTTPD using Variable

- hosts: all
  user: root
  become: yes
  gather_facts: yes
  vars:
         pkg_name: httpd
  tasks:
          - name: install HTTPD
            action: yum name='{{pkg_name}}' state=present
